# Generated by Django 4.1.2 on 2022-10-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
