# Generated by Django 4.1.2 on 2022-10-21 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HungrezyApp', '0002_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
