# Generated by Django 4.1.1 on 2022-10-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0004_restaurant_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='restaurant',
        ),
    ]
