# Generated by Django 4.1.2 on 2022-10-22 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HungrezyApp', '0007_home_made_food_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='rider',
            fields=[
                ('rid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('order_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HungrezyApp.order')),
            ],
        ),
    ]
