# Generated by Django 4.1.2 on 2022-10-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0008_menu_alter_admin_address_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
