# Generated by Django 4.1.2 on 2022-12-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0010_restaurant_or_homemade_food_delete_home_made_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_or_homemade_food',
            name='email',
        ),
    ]
