# Generated by Django 4.1.2 on 2022-12-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0011_remove_restaurant_or_homemade_food_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='some_value', max_length=50, null=True),
        ),
    ]
