# Generated by Django 4.1.2 on 2022-12-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0012_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_or_homemade_food',
            name='user',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='restaurant_or_homemade_food',
        ),
    ]
