# Generated by Django 4.1.2 on 2022-12-06 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HungrezyApp', '0013_remove_restaurant_or_homemade_food_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant_or_homemade_food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
                ('types', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='some_value', max_length=50, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
