# Generated by Django 4.1.2 on 2022-12-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0015_alter_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
