# Generated by Django 4.1.1 on 2022-12-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0017_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rider',
        ),
    ]
