# Generated by Django 4.1.1 on 2022-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0020_business_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
