# Generated by Django 4.1.1 on 2022-12-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0021_alter_customer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='business_account',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
