# Generated by Django 4.1.1 on 2022-12-08 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HungrezyApp', '0022_delete_business_account_alter_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_account',
            fields=[
                ('bus_acc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('res_name', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=20)),
                ('food_type', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
