# Generated by Django 4.1.1 on 2022-12-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0023_business_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='name',
            new_name='u_name',
        ),
    ]
