# Generated by Django 4.1.2 on 2022-12-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungrezyApp', '0027_remove_business_account_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_account',
            name='gender',
        ),
    ]
